version: '3.4'

services:
  aprp.web:
    image: ${DOCKER_REGISTRY-}aprpweb
    build:
      context: .
      dockerfile: APRP.Web/Dockerfile
    ports:
        - "80:80"
        - "443:443"
    extra_hosts:
        - "host.docker.internal:host-gateway"